//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLBB.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogContact", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class BlogContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactAddress {
            get {
                return this.ContactAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactAddressField, value) != true)) {
                    this.ContactAddressField = value;
                    this.RaisePropertyChanged("ContactAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactDate {
            get {
                return this.ContactDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDateField, value) != true)) {
                    this.ContactDateField = value;
                    this.RaisePropertyChanged("ContactDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactDay {
            get {
                return this.ContactDayField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDayField, value) != true)) {
                    this.ContactDayField = value;
                    this.RaisePropertyChanged("ContactDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogBudget", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class BlogBudget : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetBillExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetEduExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetFoodExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetInternetExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetMedicalExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetMisExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetNetIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetRIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetSourceOfIncomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetBillExp {
            get {
                return this.BudgetBillExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetBillExpField, value) != true)) {
                    this.BudgetBillExpField = value;
                    this.RaisePropertyChanged("BudgetBillExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetDate {
            get {
                return this.BudgetDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetDateField, value) != true)) {
                    this.BudgetDateField = value;
                    this.RaisePropertyChanged("BudgetDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetEduExp {
            get {
                return this.BudgetEduExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetEduExpField, value) != true)) {
                    this.BudgetEduExpField = value;
                    this.RaisePropertyChanged("BudgetEduExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetFoodExp {
            get {
                return this.BudgetFoodExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetFoodExpField, value) != true)) {
                    this.BudgetFoodExpField = value;
                    this.RaisePropertyChanged("BudgetFoodExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetInternetExp {
            get {
                return this.BudgetInternetExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetInternetExpField, value) != true)) {
                    this.BudgetInternetExpField = value;
                    this.RaisePropertyChanged("BudgetInternetExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetMedicalExp {
            get {
                return this.BudgetMedicalExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetMedicalExpField, value) != true)) {
                    this.BudgetMedicalExpField = value;
                    this.RaisePropertyChanged("BudgetMedicalExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetMisExp {
            get {
                return this.BudgetMisExpField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetMisExpField, value) != true)) {
                    this.BudgetMisExpField = value;
                    this.RaisePropertyChanged("BudgetMisExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetNetIncome {
            get {
                return this.BudgetNetIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetNetIncomeField, value) != true)) {
                    this.BudgetNetIncomeField = value;
                    this.RaisePropertyChanged("BudgetNetIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetRIncome {
            get {
                return this.BudgetRIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetRIncomeField, value) != true)) {
                    this.BudgetRIncomeField = value;
                    this.RaisePropertyChanged("BudgetRIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetSourceOfIncome {
            get {
                return this.BudgetSourceOfIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetSourceOfIncomeField, value) != true)) {
                    this.BudgetSourceOfIncomeField = value;
                    this.RaisePropertyChanged("BudgetSourceOfIncome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogEvents", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class BlogEvents : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventCategory {
            get {
                return this.EventCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.EventCategoryField, value) != true)) {
                    this.EventCategoryField = value;
                    this.RaisePropertyChanged("EventCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventDay {
            get {
                return this.EventDayField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDayField, value) != true)) {
                    this.EventDayField = value;
                    this.RaisePropertyChanged("EventDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventMonth {
            get {
                return this.EventMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.EventMonthField, value) != true)) {
                    this.EventMonthField = value;
                    this.RaisePropertyChanged("EventMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTimeField, value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventYear {
            get {
                return this.EventYearField;
            }
            set {
                if ((object.ReferenceEquals(this.EventYearField, value) != true)) {
                    this.EventYearField = value;
                    this.RaisePropertyChanged("EventYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogNotes", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class BlogNotes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesnotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotesDate {
            get {
                return this.NotesDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesDateField, value) != true)) {
                    this.NotesDateField = value;
                    this.RaisePropertyChanged("NotesDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotesDay {
            get {
                return this.NotesDayField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesDayField, value) != true)) {
                    this.NotesDayField = value;
                    this.RaisePropertyChanged("NotesDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notesnotes {
            get {
                return this.NotesnotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesnotesField, value) != true)) {
                    this.NotesnotesField = value;
                    this.RaisePropertyChanged("Notesnotes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogUser", Namespace="http://schemas.datacontract.org/2004/07/LLBBServer")]
    [System.SerializableAttribute()]
    public partial class BlogUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserUNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAddress {
            get {
                return this.UserAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddressField, value) != true)) {
                    this.UserAddressField = value;
                    this.RaisePropertyChanged("UserAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCPassword {
            get {
                return this.UserCPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCPasswordField, value) != true)) {
                    this.UserCPasswordField = value;
                    this.RaisePropertyChanged("UserCPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDOB {
            get {
                return this.UserDOBField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDOBField, value) != true)) {
                    this.UserDOBField = value;
                    this.RaisePropertyChanged("UserDOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFName {
            get {
                return this.UserFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFNameField, value) != true)) {
                    this.UserFNameField = value;
                    this.RaisePropertyChanged("UserFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLName {
            get {
                return this.UserLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLNameField, value) != true)) {
                    this.UserLNameField = value;
                    this.RaisePropertyChanged("UserLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserUName {
            get {
                return this.UserUNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserUNameField, value) != true)) {
                    this.UserUNameField = value;
                    this.RaisePropertyChanged("UserUName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        LLBB.ServiceReference1.CompositeType GetDataUsingDataContract(LLBB.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<LLBB.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(LLBB.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContactlist", ReplyAction="http://tempuri.org/IService1/getContactlistResponse")]
        LLBB.ServiceReference1.BlogContact[] getContactlist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContactlist", ReplyAction="http://tempuri.org/IService1/getContactlistResponse")]
        System.Threading.Tasks.Task<LLBB.ServiceReference1.BlogContact[]> getContactlistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddContact", ReplyAction="http://tempuri.org/IService1/AddContactResponse")]
        void AddContact(LLBB.ServiceReference1.BlogContact contact, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddContact", ReplyAction="http://tempuri.org/IService1/AddContactResponse")]
        System.Threading.Tasks.Task AddContactAsync(LLBB.ServiceReference1.BlogContact contact, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBudget", ReplyAction="http://tempuri.org/IService1/AddBudgetResponse")]
        void AddBudget(LLBB.ServiceReference1.BlogBudget budget, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBudget", ReplyAction="http://tempuri.org/IService1/AddBudgetResponse")]
        System.Threading.Tasks.Task AddBudgetAsync(LLBB.ServiceReference1.BlogBudget budget, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        void AddEvent(LLBB.ServiceReference1.BlogEvents Event, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        System.Threading.Tasks.Task AddEventAsync(LLBB.ServiceReference1.BlogEvents Event, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNotes", ReplyAction="http://tempuri.org/IService1/AddNotesResponse")]
        void AddNotes(LLBB.ServiceReference1.BlogNotes note, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNotes", ReplyAction="http://tempuri.org/IService1/AddNotesResponse")]
        System.Threading.Tasks.Task AddNotesAsync(LLBB.ServiceReference1.BlogNotes note, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        void AddUser(LLBB.ServiceReference1.BlogUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(LLBB.ServiceReference1.BlogUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteContact", ReplyAction="http://tempuri.org/IService1/DeleteContactResponse")]
        void DeleteContact(string id, LLBB.ServiceReference1.BlogContact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteContact", ReplyAction="http://tempuri.org/IService1/DeleteContactResponse")]
        System.Threading.Tasks.Task DeleteContactAsync(string id, LLBB.ServiceReference1.BlogContact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBudget", ReplyAction="http://tempuri.org/IService1/DeleteBudgetResponse")]
        void DeleteBudget(string id, LLBB.ServiceReference1.BlogBudget budget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBudget", ReplyAction="http://tempuri.org/IService1/DeleteBudgetResponse")]
        System.Threading.Tasks.Task DeleteBudgetAsync(string id, LLBB.ServiceReference1.BlogBudget budget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEvent", ReplyAction="http://tempuri.org/IService1/DeleteEventResponse")]
        void DeleteEvent(string id, LLBB.ServiceReference1.BlogEvents events);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEvent", ReplyAction="http://tempuri.org/IService1/DeleteEventResponse")]
        System.Threading.Tasks.Task DeleteEventAsync(string id, LLBB.ServiceReference1.BlogEvents events);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteNotes", ReplyAction="http://tempuri.org/IService1/DeleteNotesResponse")]
        void DeleteNotes(string id, LLBB.ServiceReference1.BlogNotes notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteNotes", ReplyAction="http://tempuri.org/IService1/DeleteNotesResponse")]
        System.Threading.Tasks.Task DeleteNotesAsync(string id, LLBB.ServiceReference1.BlogNotes notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(LLBB.ServiceReference1.BlogUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(LLBB.ServiceReference1.BlogUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditContact", ReplyAction="http://tempuri.org/IService1/EditContactResponse")]
        void EditContact(LLBB.ServiceReference1.BlogContact contact, string id, string name, string phone, string day, string date, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditContact", ReplyAction="http://tempuri.org/IService1/EditContactResponse")]
        System.Threading.Tasks.Task EditContactAsync(LLBB.ServiceReference1.BlogContact contact, string id, string name, string phone, string day, string date, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditBudget", ReplyAction="http://tempuri.org/IService1/EditBudgetResponse")]
        void EditBudget(LLBB.ServiceReference1.BlogBudget budget, string id, string SOI, string NI, string Bill, string Internet, string Medical, string Education, string Food, string Misc, string RIncome, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditBudget", ReplyAction="http://tempuri.org/IService1/EditBudgetResponse")]
        System.Threading.Tasks.Task EditBudgetAsync(LLBB.ServiceReference1.BlogBudget budget, string id, string SOI, string NI, string Bill, string Internet, string Medical, string Education, string Food, string Misc, string RIncome, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEvent", ReplyAction="http://tempuri.org/IService1/EditEventResponse")]
        void EditEvent(LLBB.ServiceReference1.BlogEvents Event, string id, string Category, string DayNo, string MonNo, string Year, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEvent", ReplyAction="http://tempuri.org/IService1/EditEventResponse")]
        System.Threading.Tasks.Task EditEventAsync(LLBB.ServiceReference1.BlogEvents Event, string id, string Category, string DayNo, string MonNo, string Year, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditNotes", ReplyAction="http://tempuri.org/IService1/EditNotesResponse")]
        void EditNotes(LLBB.ServiceReference1.BlogNotes Note, string id, string date, string Day, string Notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditNotes", ReplyAction="http://tempuri.org/IService1/EditNotesResponse")]
        System.Threading.Tasks.Task EditNotesAsync(LLBB.ServiceReference1.BlogNotes Note, string id, string date, string Day, string Notes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LLBB.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LLBB.ServiceReference1.IService1>, LLBB.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public LLBB.ServiceReference1.CompositeType GetDataUsingDataContract(LLBB.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<LLBB.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(LLBB.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public LLBB.ServiceReference1.BlogContact[] getContactlist() {
            return base.Channel.getContactlist();
        }
        
        public System.Threading.Tasks.Task<LLBB.ServiceReference1.BlogContact[]> getContactlistAsync() {
            return base.Channel.getContactlistAsync();
        }
        
        public void AddContact(LLBB.ServiceReference1.BlogContact contact, string UserID) {
            base.Channel.AddContact(contact, UserID);
        }
        
        public System.Threading.Tasks.Task AddContactAsync(LLBB.ServiceReference1.BlogContact contact, string UserID) {
            return base.Channel.AddContactAsync(contact, UserID);
        }
        
        public void AddBudget(LLBB.ServiceReference1.BlogBudget budget, string UserID) {
            base.Channel.AddBudget(budget, UserID);
        }
        
        public System.Threading.Tasks.Task AddBudgetAsync(LLBB.ServiceReference1.BlogBudget budget, string UserID) {
            return base.Channel.AddBudgetAsync(budget, UserID);
        }
        
        public void AddEvent(LLBB.ServiceReference1.BlogEvents Event, string UserID) {
            base.Channel.AddEvent(Event, UserID);
        }
        
        public System.Threading.Tasks.Task AddEventAsync(LLBB.ServiceReference1.BlogEvents Event, string UserID) {
            return base.Channel.AddEventAsync(Event, UserID);
        }
        
        public void AddNotes(LLBB.ServiceReference1.BlogNotes note, string UserID) {
            base.Channel.AddNotes(note, UserID);
        }
        
        public System.Threading.Tasks.Task AddNotesAsync(LLBB.ServiceReference1.BlogNotes note, string UserID) {
            return base.Channel.AddNotesAsync(note, UserID);
        }
        
        public void AddUser(LLBB.ServiceReference1.BlogUser user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(LLBB.ServiceReference1.BlogUser user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void DeleteContact(string id, LLBB.ServiceReference1.BlogContact contact) {
            base.Channel.DeleteContact(id, contact);
        }
        
        public System.Threading.Tasks.Task DeleteContactAsync(string id, LLBB.ServiceReference1.BlogContact contact) {
            return base.Channel.DeleteContactAsync(id, contact);
        }
        
        public void DeleteBudget(string id, LLBB.ServiceReference1.BlogBudget budget) {
            base.Channel.DeleteBudget(id, budget);
        }
        
        public System.Threading.Tasks.Task DeleteBudgetAsync(string id, LLBB.ServiceReference1.BlogBudget budget) {
            return base.Channel.DeleteBudgetAsync(id, budget);
        }
        
        public void DeleteEvent(string id, LLBB.ServiceReference1.BlogEvents events) {
            base.Channel.DeleteEvent(id, events);
        }
        
        public System.Threading.Tasks.Task DeleteEventAsync(string id, LLBB.ServiceReference1.BlogEvents events) {
            return base.Channel.DeleteEventAsync(id, events);
        }
        
        public void DeleteNotes(string id, LLBB.ServiceReference1.BlogNotes notes) {
            base.Channel.DeleteNotes(id, notes);
        }
        
        public System.Threading.Tasks.Task DeleteNotesAsync(string id, LLBB.ServiceReference1.BlogNotes notes) {
            return base.Channel.DeleteNotesAsync(id, notes);
        }
        
        public void DeleteUser(LLBB.ServiceReference1.BlogUser user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(LLBB.ServiceReference1.BlogUser user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void EditContact(LLBB.ServiceReference1.BlogContact contact, string id, string name, string phone, string day, string date, string address) {
            base.Channel.EditContact(contact, id, name, phone, day, date, address);
        }
        
        public System.Threading.Tasks.Task EditContactAsync(LLBB.ServiceReference1.BlogContact contact, string id, string name, string phone, string day, string date, string address) {
            return base.Channel.EditContactAsync(contact, id, name, phone, day, date, address);
        }
        
        public void EditBudget(LLBB.ServiceReference1.BlogBudget budget, string id, string SOI, string NI, string Bill, string Internet, string Medical, string Education, string Food, string Misc, string RIncome, string Date) {
            base.Channel.EditBudget(budget, id, SOI, NI, Bill, Internet, Medical, Education, Food, Misc, RIncome, Date);
        }
        
        public System.Threading.Tasks.Task EditBudgetAsync(LLBB.ServiceReference1.BlogBudget budget, string id, string SOI, string NI, string Bill, string Internet, string Medical, string Education, string Food, string Misc, string RIncome, string Date) {
            return base.Channel.EditBudgetAsync(budget, id, SOI, NI, Bill, Internet, Medical, Education, Food, Misc, RIncome, Date);
        }
        
        public void EditEvent(LLBB.ServiceReference1.BlogEvents Event, string id, string Category, string DayNo, string MonNo, string Year, string time) {
            base.Channel.EditEvent(Event, id, Category, DayNo, MonNo, Year, time);
        }
        
        public System.Threading.Tasks.Task EditEventAsync(LLBB.ServiceReference1.BlogEvents Event, string id, string Category, string DayNo, string MonNo, string Year, string time) {
            return base.Channel.EditEventAsync(Event, id, Category, DayNo, MonNo, Year, time);
        }
        
        public void EditNotes(LLBB.ServiceReference1.BlogNotes Note, string id, string date, string Day, string Notes) {
            base.Channel.EditNotes(Note, id, date, Day, Notes);
        }
        
        public System.Threading.Tasks.Task EditNotesAsync(LLBB.ServiceReference1.BlogNotes Note, string id, string date, string Day, string Notes) {
            return base.Channel.EditNotesAsync(Note, id, date, Day, Notes);
        }
    }
}
